### ISSUE TITLE
Any pointers for files to use in GRCh38 context ?

### ISSUE THREAD

**Issue by af8** [naumanjaved/fingerprint_maps#3]
Hi,
Is it possible to apply your script with hg38 and do you know if required files are available somewhere ?

Thank you,
Anthony

**Comment by naumanjaved** [comment]
Hi Anthony,

The hg38 VCFs are available [here](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/).

Unfortunately I do not know genetic recombination maps are available for hg38. You may be able to use the [hg19 maps](http://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3/) and convert them to hg38 using the UCSC liftover tool with an approach similar to what is described [here](https://github.com/statgen/locuszoom-standalone/issues/1).

If liftover is unsuccesful, then you can modify the script to use kb coordinates instead of cM as follows:
1. In create_PLINK_binary() on line 173 of map_building_functions.py, change
```python

plink_command = "plink --vcf " \
                    + int_directory + chrom + ".recode_u.vcf" \
                    + " --cm-map " + recomb_file \
                    + " --make-bed" \
                    + " --out " + int_directory + chrom
```
to

```python
plink_command = "plink --vcf " \
                    + int_directory + chrom + ".recode_u.vcf" \
                    + " --make-bed" \
                    + " --out " + int_directory + chrom
```
2. In LD_score() on line 180 of map_building_functions.py, change 
```python
LD_command = "python " + LD_script \
                 + " --bfile " + int_directory + chrom \
                 + " --ld-wind-cm " + str(window_cm) \
                 + " --out " + int_directory + "LD-" + chrom \
                 + " --l2 --yes-really"
```
to

```python
LD_command = "python " + LD_script \
                 + " --bfile " + int_directory + chrom \
                 + " --ld-wind-kb " + str(window_cm) \
                 + " --out " + int_directory + "LD-" + chrom \
                 + " --l2 --yes-really" 
```
This modified script will just ignore the hg19 recombination map and calculate LDScore over a window with size specified in kb(just set --window_cm to a kilobase equivalent of whatever your original window size was, i.e. 1.0 cm ~ 1000 kb). 

Hope this helps,
Nauman
